name: Second workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download code
      - uses: actions/checkout@v4
      - name: install dependencies
      - run: npm install
      - name: run tests
      - run: npm run test